<?xml version="1.0" ?>
<!--
The MIT License
Copyright (c) 2022 Giovanni di Dio Bruno https://gbr1.github.io
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->
<robot name="upcreate3" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="CREATE3_TOP_Z" value="0.0934"/>
  <xacro:property name="CREATE3_GRID" value="0.012"/>

  <xacro:property name="BRACKET_GRID_X" value="-6.5"/>
  <xacro:property name="BRACKET_GRID_Y" value="0"/>


  <!-- iRobot Create3 -->
  <xacro:include filename="$(find irobot_create_description)/urdf/create3.urdf.xacro" />
  <!-- Bracket for Realsense camera -->
  <xacro:include filename="$(find upcreate3_description)/urdf/parts/realsense_bracket.urdf.xacro" />
  <!-- Realsense -->
  <xacro:include filename="$(find upcreate3_description)/urdf/sensors/realsense.urdf.xacro" />

  <xacro:realsense_bracket />
    <joint name="realsense_bracket_base_joint" type="fixed">
        <origin xyz="${BRACKET_GRID_X*CREATE3_GRID}  ${BRACKET_GRID_Y*CREATE3_GRID} ${CREATE3_TOP_Z}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="realsense_bracket_base" />
    </joint>


</robot>
